name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see
      placeholder: What would you like to add or improve?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be useful?
      placeholder: This would help with...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution (optional)
      description: Do you have an idea of how this could be implemented?
      placeholder: Maybe we could...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions (optional)
      description: Are there other ways to accomplish this?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (optional)
      description: Any other context, screenshots, or illustrations that can help explain your idea
